version: '3.8'

services:
  backend:
    build: ./backend
    container_name: amazona_backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env # Securely passes your MongoDB Atlas URI to the container
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: amazona_frontend
    ports:
      - "80:80"  # Changes the external "door" from 3000 to 80
    depends_on:
      - backend
    restart: unless-stopped